(()=>{const U="https://rmhuaidhengblkxnottb.supabase.co",K="sb_publishable_VF_LvBGscM5fZXtYptaFjg_TB1s5NwD",base=WB_SUPPORT_KNOWLEDGE_V2.situations||[];let db,busy=false;const id=p=>p+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7),csv=v=>String(v||"").split(",").map(x=>x.trim()).filter(Boolean),clean=x=>({id:x.id,audience:x.audience,category:x.category,group:x.group,title:x.title,path:[x.category,x.group,x.title],description:x.description||"",theme:x.theme||"",officialTaxonomy:x.officialTaxonomy||[],aliases:x.aliases||[],tags:x.tags||[],roadmap:x.roadmap||{},answers:x.answers||[]});
async function load(active){let q=await db.from("situations").select("data").order("updated_at");if(q.error){console.error(q.error);toast("Сначала выполните supabase-schema.sql");return set(base)}if(!q.data.length){for(let i=0;i<base.length;i+=20){let z=await db.from("situations").upsert(base.slice(i,i+20).map(x=>({id:x.id,data:clean(x)})));if(z.error)return toast("Не удалось загрузить базу: "+z.error.message)}return load(active)}set(q.data.map(x=>x.data),active)}
function set(a,active){state.data=normalizeData({situations:a});state.activeId=active||state.activeId;sync();render();paint()}
async function save(x){let d=clean(x),q=await db.from("situations").upsert({id:d.id,data:d});if(q.error)return toast("Не сохранено: "+q.error.message);await load(d.id);toast("Сохранено")}
async function remove(x){let q=await db.from("situations").delete().eq("id",x.id);if(q.error)return toast("Не удалено: "+q.error.message);await load();toast("Удалено")}
function f(n,l,v="",a=false){return"<label>"+l+(a?'<textarea name="'+n+'">'+escapeHtml(v)+"</textarea>":'<input name="'+n+'" value="'+escapeHtml(v)+'">')+"</label>"}
function modal(title,html,fn){let d=document.createElement("dialog");d.className="crud";d.innerHTML="<form><h3>"+title+"</h3>"+html+"<footer><button type=button>Отмена</button><button>Сохранить</button></footer></form>";document.body.append(d);d.querySelector("[type=button]").onclick=()=>d.remove();d.querySelector("form").onsubmit=async e=>{e.preventDefault();await fn(Object.fromEntries(new FormData(e.target)));d.remove()};d.showModal()}
function paint(){document.querySelectorAll(".crud-action").forEach(n=>n.remove());let x=getActiveSituation();if(!x)return;let h=document.querySelector(".article-head"),e=document.createElement("button"),d=document.createElement("button");e.className="icon-button crud-action";e.textContent="✎";e.title="Изменить тематику";e.onclick=()=>editSituation(x);d.className="icon-button crud-action danger";d.textContent="⌫";d.title="Удалить тематику";d.onclick=()=>{if(confirm("Удалить тематику?"))remove(x)};h.append(e,d);let st=document.querySelector(".answers .section-title"),a=document.createElement("button");a.className="crud-action addMac";a.textContent="＋ Макрос";a.onclick=()=>editMacro(x);st.append(a);document.querySelectorAll(".answer-item").forEach((n,i)=>{let q=document.createElement("span"),eb=document.createElement("button"),db=document.createElement("button");q.className="crud-action rowedit";eb.textContent="✎";eb.onclick=()=>editMacro(x,x.answers[i]);db.textContent="⌫";db.className="danger";db.onclick=()=>{if(x.answers.length<2)return toast("Нельзя удалить единственный макрос");if(confirm("Удалить макрос?")){x.answers.splice(i,1);save(x)}};q.append(eb,db);n.querySelector(".answer-head").append(q)});let th=document.querySelector(".tree-heading"),nb=document.createElement("button");nb.className="crud-action addTopic";nb.textContent="＋";nb.title="Добавить тематику";nb.onclick=newTopic;th.append(nb)}
function editSituation(x){modal("Изменить тематику и теги",f("title","Название",x.title)+f("theme","Тематика",x.theme)+f("category","Раздел базы",x.category)+f("group","Подраздел",x.group)+f("tags","Теги через запятую",(x.tags||[]).join(", "))+f("description","Описание",x.description,true),v=>{Object.assign(x,v,{tags:csv(v.tags),path:[v.category,v.group,v.title]});return save(x)})}
function editMacro(x,a){a=a||{id:id("macro"),stage:"initial",title:"",ru:"",uz:""};modal(a.title?"Изменить макрос":"Добавить макрос",f("title","Название",a.title)+f("stage","Этап",a.stage)+f("ru","Русский текст",a.ru,true)+f("uz","O‘zbekcha matn",a.uz,true),v=>{Object.assign(a,v);if(!x.answers.some(y=>y.id===a.id))x.answers.push(a);return save(x)})}
function newTopic(){modal("Добавить тематику",f("category","Раздел базы")+f("group","Подраздел","Общее")+f("title","Название"),v=>save({id:id("situation"),audience:state.audience,...v,theme:v.title,path:[v.category,v.group,v.title],tags:[],answers:[{id:id("macro"),stage:"initial",title:"Новый макрос",ru:"Заполните текст",uz:""}]}))}
document.addEventListener("DOMContentLoaded",async()=>{if(!window.supabase)return toast("Supabase не загрузился");db=supabase.createClient(U,K);await load();let o=new MutationObserver(()=>{if(busy)return;busy=true;o.disconnect();paint();o.observe(document.body,{childList:true,subtree:true});busy=false});paint();o.observe(document.body,{childList:true,subtree:true})})})();