(()=>{"use strict";const U="https://rmhuaidhengblkxnottb.supabase.co",K="sb_publishable_VF_LvBGscM5fZXtYptaFjg_TB1s5NwD",base=WB_SUPPORT_KNOWLEDGE_V2.situations||[],MODE="wb.editor",BID="wb.browser";let db,all=[],editor=localStorage.getItem(MODE)==="1",tag="",translation="all",busy=false;const bid=localStorage.getItem(BID)||("browser-"+crypto.randomUUID());localStorage.setItem(BID,bid);const uid=p=>p+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7),csv=v=>String(v||"").split(",").map(x=>x.trim()).filter(Boolean),clean=x=>({id:x.id,audience:x.audience,category:x.category,group:x.group,title:x.title,path:[x.category,x.group,x.title],description:x.description||"",theme:x.theme||"",officialTaxonomy:x.officialTaxonomy||[],aliases:x.aliases||[],tags:x.tags||[],roadmap:x.roadmap||{},answers:x.answers||[],_deletedAt:x._deletedAt||null});
function filtered(){return all.filter(x=>!x._deletedAt).filter(x=>!tag||(x.tags||[]).includes(tag)).map(x=>translation==="missing"?{...x,answers:(x.answers||[]).filter(a=>!a.uz||!a.ru)}:x).filter(x=>translation!=="missing"||x.answers.length)}
function set(active){state.data=normalizeData({situations:filtered()});state.activeId=active||state.activeId;sync();render();paint()}
async function load(active){let q=await db.from("situations").select("data").order("updated_at");if(q.error){console.error(q.error);toast("Ошибка Supabase");all=base;return set(active)}all=q.data.map(x=>x.data);if(!all.length){await upsert(base,false);return load(active)}set(active)}
async function audit(action,id,before,after){let q=await db.from("audit_logs").insert({action,entity_id:id,before_data:before||null,after_data:after||null,browser_id:bid});if(q.error)console.warn("Audit unavailable",q.error.message)}
async function save(x,action="update",before=null){let d=clean(x),q=await db.from("situations").upsert({id:d.id,data:d});if(q.error)return toast("Не сохранено: "+q.error.message);await audit(action,d.id,before,d);await load(d.id);toast("Сохранено")}
async function upsert(items,log=true){for(let i=0;i<items.length;i+=20){let batch=items.slice(i,i+20).map(x=>({id:x.id,data:clean(x)})),q=await db.from("situations").upsert(batch);if(q.error)throw q.error}if(log)await audit("import","bulk",null,{count:items.length})}
const field=(n,l,v="",type="input")=>"<label>"+l+(type==="area"?'<textarea name="'+n+'">'+escapeHtml(v)+"</textarea>":type==="select"?'<select name="'+n+'>'+v+"</select>":'<input name="'+n+'" value="'+escapeHtml(v)+'">')+"</label>";
function modal(title,html,fn){let d=document.createElement("dialog");d.className="crud";d.innerHTML="<form><header><h3>"+title+"</h3><button type=button class=close>×</button></header><div class=fields>"+html+"</div><footer><button type=button class=cancel>Отмена</button><button class=primary>Сохранить</button></footer></form>";document.body.append(d);let dirty=false;d.querySelector("form").oninput=()=>dirty=true;let close=()=>{if(!dirty||confirm("Закрыть без сохранения?"))d.remove()};d.querySelectorAll("[type=button]").forEach(b=>b.onclick=close);d.querySelector("form").onsubmit=async e=>{e.preventDefault();let ok=await fn(Object.fromEntries(new FormData(e.target)));if(ok!==false)d.remove()};d.showModal()}
function paint(){document.querySelectorAll(".crud-action").forEach(n=>n.remove());let bar=document.querySelector(".toolbar");if(bar&&!bar.querySelector(".adminbar")){let a=document.createElement("div");a.className="adminbar";a.innerHTML='<button data-tool=mode></button><button data-tool=export>Экспорт</button><button data-tool=import>Импорт</button><button data-tool=history>История</button><button data-tool=trash>Корзина</button><input type=file accept=".json" hidden>';bar.prepend(a)}let mb=document.querySelector("[data-tool=mode]");if(mb)mb.textContent=editor?"Редактор: вкл":"Редактор: выкл";let side=document.querySelector(".search-box");if(side&&!document.querySelector(".kbfilters")){let tags=[...new Set(all.flatMap(x=>x.tags||[]))].sort();let f=document.createElement("div");f.className="kbfilters";f.innerHTML='<select id=tagFilter><option value="">Все теги</option>'+tags.map(x=>'<option>'+escapeHtml(x)+"</option>").join("")+'</select><select id=translationFilter><option value=all>Все переводы</option><option value=missing>Нет RU или UZ</option></select>';side.after(f);f.onchange=e=>{if(e.target.id==="tagFilter")tag=e.target.value;else translation=e.target.value;set()}}if(!editor)return;let x=getActiveSituation();if(!x)return;let h=document.querySelector(".article-head");add(h,"✎","edit",()=>editSituation(x),"Изменить");add(h,"⌫","delete",()=>drop(x),"Удалить");let st=document.querySelector(".answers .section-title");add(st,"＋ Макрос","add",()=>editMacro(x),"Добавить макрос");document.querySelectorAll(".answer-item").forEach((n,i)=>{let q=document.createElement("span");q.className="crud-action rowedit";[["✎",()=>editMacro(x,x.answers[i])],["⧉",()=>duplicate(x,i)],["↑",()=>move(x,i,-1)],["↓",()=>move(x,i,1)],["⌫",()=>deleteMacro(x,i)]].forEach(z=>add(q,z[0],"",z[1]));n.querySelector(".answer-head").append(q)});let th=document.querySelector(".tree-heading");add(th,"＋","topic",newTopic,"Добавить тематику");add(th,"⚙","category",manageCategory,"Разделы")}
function add(p,t,c,fn,title=""){let b=document.createElement("button");b.type="button";b.textContent=t;b.className="crud-action "+c;b.title=title;b.onclick=fn;p.append(b)}
function editSituation(x){let before=structuredClone(x);modal("Изменить тематику и теги",field("title","Название",x.title)+field("theme","Тематика",x.theme)+field("category","Раздел базы",x.category)+field("group","Подраздел",x.group)+field("tags","Теги через запятую",(x.tags||[]).join(", "))+field("taxonomy","Возможные тематики",(x.officialTaxonomy||[]).join(", "))+field("description","Описание",x.description,"area"),v=>{if(!v.title.trim()||!v.category.trim())return toast("Заполните название и раздел"),false;Object.assign(x,v,{tags:csv(v.tags),officialTaxonomy:csv(v.taxonomy),path:[v.category,v.group||"Общее",v.title]});return save(x,"update_topic",before)})}
function editMacro(x,a){let fresh=!a,before=structuredClone(x);a=a||{id:uid("macro"),stage:"initial",title:"",ru:"",uz:""};modal(fresh?"Добавить макрос":"Изменить макрос",field("title","Название",a.title)+field("stage","Этап",a.stage)+field("ru","Русский текст",a.ru,"area")+field("uz","O‘zbekcha matn",a.uz,"area"),v=>{if(!v.title.trim()||(!v.ru.trim()&&!v.uz.trim()))return toast("Заполните название и текст"),false;if(x.answers.some(y=>y.id!==a.id&&y.title.trim().toLowerCase()===v.title.trim().toLowerCase()))return toast("Макрос с таким названием уже есть"),false;Object.assign(a,v);if(fresh)x.answers.push(a);return save(x,fresh?"create_macro":"update_macro",before)})}
function duplicate(x,i){let before=structuredClone(x),a=structuredClone(x.answers[i]);a.id=uid("macro");a.title+=" — копия";x.answers.splice(i+1,0,a);save(x,"duplicate_macro",before)}
function move(x,i,d){let j=i+d;if(j<0||j>=x.answers.length)return;let before=structuredClone(x);[x.answers[i],x.answers[j]]=[x.answers[j],x.answers[i]];save(x,"reorder_macro",before)}
function deleteMacro(x,i){if(x.answers.length===1)return toast("Нельзя удалить единственный макрос");if(!confirm("Удалить макрос?"))return;let before=structuredClone(x);x.answers.splice(i,1);save(x,"delete_macro",before)}
function drop(x){if(!confirm("Переместить тематику в корзину?"))return;let before=structuredClone(x);x._deletedAt=new Date().toISOString();save(x,"trash_topic",before)}
function newTopic(){modal("Добавить тематику",field("category","Раздел базы")+field("group","Подраздел","Общее")+field("title","Название"),v=>{if(!v.category.trim()||!v.title.trim())return false;let x={id:uid("situation"),audience:state.audience,...v,theme:v.title,path:[v.category,v.group||"Общее",v.title],tags:[],answers:[{id:uid("macro"),stage:"initial",title:"Новый макрос",ru:"Заполните текст",uz:""}]};return save(x,"create_topic")})}
function manageCategory(){let opts=[...new Set(all.filter(x=>!x._deletedAt).map(x=>x.category))].sort().map(x=>'<option value="'+escapeHtml(x)+'">'+escapeHtml(x)+"</option>").join("");modal("Переименовать раздел",field("old","Раздел",opts,"select")+field("next","Новое название"),async v=>{if(!v.next.trim())return false;let items=all.filter(x=>x.category===v.old&&!x._deletedAt);for(let x of items){let before=structuredClone(x);x.category=v.next.trim();x.path=[x.category,x.group,x.title];await save(x,"rename_category",before)}return true})}
async function showTrash(){let items=all.filter(x=>x._deletedAt);let d=document.createElement("dialog");d.className="crud list";d.innerHTML="<h3>Корзина</h3>"+(items.map(x=>'<p><span>'+escapeHtml(x.title)+'</span><button data-id="'+x.id+'">Восстановить</button></p>').join("")||"<p>Корзина пуста</p>")+'<footer><button>Закрыть</button></footer>';document.body.append(d);d.querySelector("footer button").onclick=()=>d.remove();d.querySelectorAll("[data-id]").forEach(b=>b.onclick=async()=>{let x=all.find(y=>y.id===b.dataset.id),before=structuredClone(x);x._deletedAt=null;await save(x,"restore_topic",before);d.remove()});d.showModal()}
async function history(){let q=await db.from("audit_logs").select("*").order("created_at",{ascending:false}).limit(100),items=q.data||[];let d=document.createElement("dialog");d.className="crud list";d.innerHTML="<h3>История изменений</h3>"+(q.error?"<p>Выполните обновлённый SQL-файл.</p>":items.map(x=>'<p><span><b>'+escapeHtml(x.action)+"</b><small>"+new Date(x.created_at).toLocaleString()+" · "+escapeHtml(x.browser_id)+"</small></span>"+(x.before_data?'<button data-rollback="'+x.id+'">Откатить</button>':"")+"</p>").join(""))+"<footer><button>Закрыть</button></footer>";document.body.append(d);d.querySelector("footer button").onclick=()=>d.remove();d.querySelectorAll("[data-rollback]").forEach(b=>b.onclick=async()=>{let h=items.find(x=>String(x.id)===b.dataset.rollback);if(!h||!confirm("Восстановить состояние до этого изменения?"))return;let current=all.find(x=>x.id===h.entity_id)||null;await save(h.before_data,"rollback",current);d.remove()});d.showModal()}
async function dailyBackup(){let day=new Date().toISOString().slice(0,10);if(localStorage.getItem("wb.backup.day")===day)return;let q=await db.from("backup_snapshots").insert({backup_date:day,data:all,browser_id:bid});if(!q.error)localStorage.setItem("wb.backup.day",day)}
const originalCopy=copyAnswer;copyAnswer=async function(answerId,language=state.language){let s=getActiveSituation(),a=s&&s.answers.find(x=>x.id===answerId),text=getAnswerText(a||{},language),matches=[...text.matchAll(/\{\{\s*([^{}]+?)\s*\}\}/g)],names=[...new Set(matches.map(x=>x[1]))];if(!names.length)return originalCopy(answerId,language);modal("Заполните переменные",names.map(n=>field("var_"+n,n)).join(""),async v=>{let out=text;matches.forEach(m=>out=out.split(m[0]).join(v["var_"+m[1]]||""));if(await copyText(out)){openSituation(s.id);toast("Макрос заполнен и скопирован")}return true})}
function exportData(){let blob=new Blob([JSON.stringify(all.filter(x=>!x._deletedAt),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="wb-macros-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(a.href)}
async function importData(file){try{let data=JSON.parse(await file.text());if(!Array.isArray(data)||!data.every(x=>x.id&&x.title&&Array.isArray(x.answers)))throw Error("Неверный формат");if(!confirm("Импортировать "+data.length+" тематик? Совпадающие ID будут обновлены."))return;await upsert(data);await load();toast("Импорт завершён")}catch(e){toast("Ошибка импорта: "+e.message)}}
document.addEventListener("click",e=>{let b=e.target.closest("[data-tool]");if(!b)return;if(b.dataset.tool==="mode"){editor=!editor;localStorage.setItem(MODE,editor?"1":"0");paint()}if(b.dataset.tool==="export")exportData();if(b.dataset.tool==="import")document.querySelector(".adminbar input").click();if(b.dataset.tool==="history")history();if(b.dataset.tool==="trash")showTrash()});
document.addEventListener("change",e=>{if(e.target.matches(".adminbar input")&&e.target.files[0])importData(e.target.files[0])});
document.addEventListener("DOMContentLoaded",async()=>{db=supabase.createClient(U,K);await load();dailyBackup();let o=new MutationObserver(()=>{if(busy)return;busy=true;o.disconnect();paint();o.observe(document.body,{childList:true,subtree:true});busy=false});paint();o.observe(document.body,{childList:true,subtree:true})})})();